Repository airesearch-in-th/airesearch-in-th-website, pull requests merged in 2020-07, with the labels that each got.

#11 Translated navs, menus, footer, and content to Thai
  .github/workflows/jekyll-build-and-deploy-on-github-pages.yml
  .github/workflows/jekyll-build.yml
  _includes/carousel.html
  _includes/footer.html
  _includes/navbar.html
  _layouts/release.html
  _pages/contact.html
  _pages/home.html
  _releases/machine-translation-datasets.md
  _releases/machine-translation-models.md
  _resources/cpu-clusters.md
  _resources/gpu-clusters.md
  _resources/io-clusters.md
  _resources/nvidia-dgx.md
  _services/ai-consultant-and-training.md
  _services/research-translational-service.md
  assets/img/resources/hard-drive.jpg
Labels: documentation, enhancement

#12 Change sha256 due to change in columns for all csv files
  _releases/machine-translation-datasets.md
Labels: documentation, enhancement

#13 Fix typo in MT dataset article
  _releases/machine-translation-datasets.md
Labels: bug, documentation

#14 Fix sponsor logos being hidden, refactored: sponsor -> supporter
  _config.yml
  _pages/home.html
  _releases/machine-translation-datasets.md
  _sass/main.scss
  _supporters/ais.md
  _supporters/irpc.md
  _supporters/pttgc.md
  _supporters/scb.md
  assets/img/supporters/ais-logo.svg
  assets/img/supporters/irpc-logo.svg
  assets/img/supporters/pttgc-logo.svg
  assets/img/supporters/scb-logo.svg
Labels: bug

#16 Thainify 404 page
  _pages/not-found.html
Labels: enhancement

#17 Make use of correct official Thai title for the Insititute
  _includes/carousel.html
  _includes/footer.html
  _pages/home.html
  _releases/machine-translation-datasets.md
  _releases/machine-translation-models.md
Labels: documentation, enhancement

#19 feat: rework release detail page download list layout
  _layouts/release.html
  _sass/release.scss
Labels: enhancement

#20 Machine Translation API Demo
  _releases/mt-model-demo.md
Labels: enhancement
