Repository airesearch-in-th/airesearch-in-th-website, pull requests merged in 2021-03, with the labels that each got.

#32 Launch SER dataset and WangchanBERTa
  _includes/footer.html
  _includes/meta-tags.html
  _layouts/default.html
  _layouts/release.html
  _releases/speech-emotion-dataset.md
  _releases/wangchanberta-pre-trained-thai-language-model.md
  _sass/contact.scss
  _sass/footer.scss
  _sass/main.scss
  _sass/navbar.scss
  _sass/release.scss
  assets/img/releases/speech_emotion_dataset/CM_07_v1.png
  assets/img/releases/speech_emotion_dataset/CM_all_v1.png
  assets/img/releases/speech_emotion_dataset/microphone.jpg
  assets/img/releases/speech_emotion_dataset/studio_setup.png
  assets/img/releases/wangchanberta-pre-trained-thai-language-model/illustration_word-segmentation.png
  assets/img/releases/wangchanberta-pre-trained-thai-language-model/tab1_text-cls-results.png
  assets/img/releases/wangchanberta-pre-trained-thai-language-model/tab2_token-cls-results.png
  assets/img/releases/wangchanberta-pre-trained-thai-language-model/vistec-main-building.jpg
  robots.txt
Labels: documentation, enhancement

#33 Update speech-emotion-dataset.md
  _releases/speech-emotion-dataset.md
Labels: bug, documentation

#34 Fix SER references
  _releases/speech-emotion-dataset.md
Labels: bug, documentation

#35 Update speech-emotion-dataset.md
  _releases/speech-emotion-dataset.md
Labels: bug, documentation

#36 Add sponsor and crowdsourcing information to SER article
  _releases/speech-emotion-dataset.md
Labels: documentation, enhancement

#38 fix: org name in carousel
  _includes/carousel.html
Labels: documentation, enhancement

#39 add cm v1 pic
  assets/img/releases/speech_emotion_dataset/CM_071_v1.png
  assets/img/releases/speech_emotion_dataset/CM_07_v1.png
  assets/img/releases/speech_emotion_dataset/CM_all_v1.png
Labels: documentation, enhancement

#40 update stat to SER version1
  _releases/speech-emotion-dataset.md
Labels: documentation, enhancement

#42 refactor: remove unused assets
  _releases/speech-emotion-dataset.md
  assets/img/releases/speech_emotion_dataset/CM_07_v1.png
Labels: enhancement
